### ISSUE TITLE
audio/ midi influencer isnt recognizing the offset of the sample/midi file

### ISSUE THREAD

**Issue by eleusiiis** [DYCI2/Somax2#14]
I opened the somax overview patch with the 1st tutorial and everything seems to work exept the pitch/ offset recognition. somax isnt able to analyse and imrpovise with the midi file because it isnt analysing the audio. I ve checked that everything should be enabled and running but something just doesnt work. could you let me know why it's not working?

**Comment by jobor019** [comment]
Hi!

Are you using an old version of Max? Somax requires at least Max 8.3 (preferably 8.5), and the issue you describe is similar to what other users with outdated Max versions have reported. If that's the case, could you please update your version?

If this isn't the case, do you have any error messages in the Max console?

**Comment by eleusiiis** [comment]
i am currently using an 8.3 version but ill update it right now, i will let you know once if this doesnt work

**Comment by eleusiiis** [comment]
so the midi detection works but when i sue my laptops mic or a sound file somax doesnt recognize the onset. sometimes there is an error coming calles "somax.server: doesn't understand beatphase"

**Comment by jobor019** [comment]
Hm, the beatphase error is unrelated (and unproblematic) and everything looks correct with your setup.

The only thing I can think of is if you're missing something in your installation or not [running Max under rosetta](https://docs.cycling74.com/max8/vignettes/apple_arm64) on an ARM machine, but then you should really have clear errors in the console.

Could you post the full Max console output?

Also, which version of MacOS are you on? And are you using an ARM or Intel machine?

**Comment by jobor019** [comment]
Hi again!

I hope that your issue has been resolved by now as there hasn't been any further response from your side. If you're still having issues, feel free to open a new issue providing the requested information
