### ISSUE TITLE
Can't launch somax server

### ISSUE THREAD

**Issue by TomBugnon** [DYCI2/Somax2#2]
Hi,

I'm obviously missing something (since I don't understand how Max works) but I can't seem to launch the somax server properly.
I tried the 3 options in the servers' advanced settings:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/14128078/132844558-6711195e-333e-4a3b-8d52-d1b970fa81a6.png">

- With the default value: "standalone", a shell opens and shows an enormous amount of unreadable characters, the Max console says "Launching the somax server", but the server status remains "offline"
<img width="637" alt="image" src="https://user-images.githubusercontent.com/14128078/132845063-1a47721c-e193-47a0-9bfb-69d6c24754b9.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/14128078/132845078-01034cb1-ee4a-4f44-acc0-9a8809f5c4e7.png">

- With "Default python installation" I get this error in the max console
<img width="507" alt="image" src="https://user-images.githubusercontent.com/14128078/132844783-e7f34660-172a-43bc-b141-f71938c60f2b.png">

- With "Custom" python I apparently need a "shell external" but I don't understand what that means

I'm on MacOS Catalina, with Max 8 and Somax v2.3.2

Thanks
Tom

**Comment by jobor019** [comment]
Hi,

That's very odd. You're not doing anything wrong - the "Standalone" option should simply launch a pre-compiled version of the somax python code and should work without any configuration. Could you try to launch this one manually and see what happens? It's located inside the `misc` folder of the Somax package, so just run (in a terminal)

`~/Documents/Max\ 8/Packages/Somax2/misc/somax_server.app/Contents/MacOS/somax_server`

Does this work, or do you get the same messy text output?

Also, are you running the full version of Max 8 or just a trial version?

**Comment by TomBugnon** [comment]
okkkk I figured it out, as expected it's silly...!

The default app for opening the unix executable on my machine was textedit, not the terminal, so the messy output was simply the file displayed, I didn't notice it was not in the terminal 😅

 It works as expected after changing the default app for all unix exec files.
 
 Thanks for the quick response!

**Comment by jobor019** [comment]
Great to hear! Feel free to reach out if you run into any further issues!
